import "dotenv/config";
import { pool } from "../lib/db";
import type { Game } from "@padplay/shared-types";

type SeedGame = Omit<
  Game,
  | "createdAt"
  | "updatedAt"
  | "iconUrl"
  | "iosRating"
  | "iosRatingCount"
  | "androidRating"
  | "androidRatingCount"
  | "ratingsUpdatedAt"
  | "screenshots"
  | "quotes"
  | "priceUpdatedAt"
>;

const SEED_GAMES: SeedGame[] = [
  {
    slug: "civilization-vi",
    title: "Civilization VI",
    developer: "Aspyr Media / Firaxis",
    category: "strategy",
    platforms: "both",
    tabletScore: 96,
    priceUsd: 24.99,
    shortDescription:
      "Full desktop 4X experience rebuilt around touch — pinch to zoom, drag to pan, native-feeling unit commands.",
    tabletFeatures: [
      "Native touch controls",
      "Map scales to tablet screens",
      "Full DLC parity with desktop",
      "Cross-save with Steam",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/civilization-vi/id1385029932",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.aspyr.civilization_vi",
    thumbnail: "/images/games/civilization-vi.jpg",
    releaseYear: 2016,
  },
  {
    slug: "slay-the-spire",
    title: "Slay the Spire",
    developer: "Mega Crit / Humble Games",
    category: "strategy",
    platforms: "both",
    tabletScore: 94,
    priceUsd: 9.99,
    shortDescription:
      "Deckbuilder roguelike where the tablet form factor feels better than mouse — cards meet your thumb naturally.",
    tabletFeatures: [
      "Card play feels native on touch",
      "Designed HUD for portrait/landscape",
      "No shrunken desktop UI",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/slay-the-spire/id1491530147",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.humble.SlayTheSpire",
    thumbnail: "/images/games/slay-the-spire.jpg",
    releaseYear: 2020,
  },
  {
    slug: "stardew-valley",
    title: "Stardew Valley",
    developer: "ConcernedApe",
    category: "simulation",
    platforms: "both",
    tabletScore: 92,
    priceUsd: 4.99,
    shortDescription:
      "Farming sim with a dedicated tablet UI — bigger inventory grids, larger hit targets, no squinting.",
    tabletFeatures: [
      "Tablet-specific HUD scaling",
      "Controller + touch both work",
      "Cross-save to PC",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/stardew-valley/id1406710800",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.chucklefish.stardewvalley",
    thumbnail: "/images/games/stardew-valley.jpg",
    releaseYear: 2018,
  },
  {
    slug: "xcom-2-collection",
    title: "XCOM 2 Collection",
    developer: "Feral Interactive",
    category: "strategy",
    platforms: "ios",
    tabletScore: 90,
    priceUsd: 24.99,
    shortDescription:
      "Full XCOM 2 + expansion tuned for iPad Pro — touch-first unit selection, gesture camera control.",
    tabletFeatures: [
      "iPad Pro optimized",
      "Apple Silicon native",
      "Gesture-based camera",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/xcom-2-collection/id1568884321",
    playStoreUrl: null,
    thumbnail: "/images/games/xcom-2-collection.jpg",
    releaseYear: 2021,
  },
  {
    slug: "monument-valley-2",
    title: "Monument Valley 2",
    developer: "ustwo games",
    category: "puzzle",
    platforms: "both",
    tabletScore: 95,
    priceUsd: 4.99,
    shortDescription:
      "Escher-inspired puzzler built for touch. The extra real estate of a tablet makes each level a tiny museum piece.",
    tabletFeatures: [
      "Built touch-first",
      "Scales beautifully to iPad Pro",
      "Silent, no-IAP design",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/monument-valley-2/id1187265767",
    playStoreUrl:
      "https://play.google.com/store/apps/details?id=com.ustwo.monumentvalley2",
    thumbnail: "/images/games/monument-valley-2.jpg",
    releaseYear: 2017,
  },
  {
    slug: "gris",
    title: "GRIS",
    developer: "Devolver / Nomada Studio",
    category: "action",
    platforms: "both",
    tabletScore: 88,
    priceUsd: 4.99,
    shortDescription:
      "Watercolor platformer where a 12-inch display is the minimum to do the art justice.",
    tabletFeatures: [
      "Vector-scaled art for any tablet",
      "Controller + touch",
      "Haptic feedback on iPad Pro",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/gris/id1459315523",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.devolver.gris",
    thumbnail: "/images/games/gris.jpg",
    releaseYear: 2019,
  },
  {
    slug: "hearthstone",
    title: "Hearthstone",
    developer: "Blizzard Entertainment",
    category: "strategy",
    platforms: "both",
    tabletScore: 91,
    priceUsd: null,
    shortDescription:
      "Card-slinging on a tablet is how Hearthstone was always meant to be played — the board is a tabletop.",
    tabletFeatures: [
      "Wide-board HUD for tablets",
      "Battle.net cross-save",
      "High-res card art",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/hearthstone/id625257520",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.blizzard.wtcg.hearthstone",
    thumbnail: "/images/games/hearthstone.jpg",
    releaseYear: 2014,
  },
  {
    slug: "alto-odyssey",
    title: "Alto's Odyssey: The Lost City",
    developer: "Snowman",
    category: "action",
    platforms: "both",
    tabletScore: 87,
    priceUsd: null,
    shortDescription:
      "Endless sandboarder whose gorgeous vistas truly open up on a larger tablet display.",
    tabletFeatures: [
      "Designed for large screens",
      "120Hz support on iPad Pro",
      "Minimal UI",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/altos-odyssey-the-lost-city/id1514791218",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.noodlecake.altosodyssey",
    thumbnail: "/images/games/alto-odyssey.jpg",
    releaseYear: 2020,
  },
  {
    slug: "carcassonne",
    title: "Carcassonne: Tiles & Tactics",
    developer: "Asmodee Digital",
    category: "board",
    platforms: "both",
    tabletScore: 93,
    priceUsd: 9.99,
    shortDescription:
      "Board-game-on-a-table is a genre — and the tablet is the literal table. The classics always win here.",
    tabletFeatures: [
      "Board zoom made for tablets",
      "Local multiplayer pass-and-play",
      "Expansion packs parity",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/carcassonne-tiles-tactics/id1434239377",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.asmodeedigital.carcassonne",
    thumbnail: "/images/games/carcassonne.jpg",
    releaseYear: 2018,
  },
  {
    slug: "wingspan",
    title: "Wingspan",
    developer: "Monster Couch",
    category: "board",
    platforms: "both",
    tabletScore: 90,
    priceUsd: 9.99,
    shortDescription:
      "Engine-building boardgame where the tablet perfectly replicates the feel of laying tiles on a kitchen table.",
    tabletFeatures: [
      "Hand-tuned tablet HUD",
      "Pass-and-play for groups",
      "Full expansions in-app",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/wingspan-the-board-game/id1515347676",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.monstercouch.wingspan",
    thumbnail: "/images/games/wingspan.jpg",
    releaseYear: 2020,
  },
  {
    slug: "disco-elysium",
    title: "Disco Elysium",
    developer: "ZA/UM",
    category: "rpg",
    platforms: "ios",
    tabletScore: 89,
    priceUsd: 29.99,
    shortDescription:
      "Text-heavy RPG where a 12.9\" iPad is the minimum viable screen for the dialogue density.",
    tabletFeatures: [
      "iPad Pro optimized",
      "Full text readability",
      "Cross-save to PC",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/disco-elysium-the-final-cut/id1568836469",
    playStoreUrl: null,
    thumbnail: "/images/games/disco-elysium.jpg",
    releaseYear: 2022,
  },
  {
    slug: "baldurs-gate-enhanced",
    title: "Baldur's Gate: Enhanced Edition",
    developer: "Beamdog",
    category: "rpg",
    platforms: "both",
    tabletScore: 86,
    priceUsd: 9.99,
    shortDescription:
      "Classic Infinity Engine CRPG with a tablet UI rework — not just a port, a proper retuning.",
    tabletFeatures: [
      "Tablet-specific HUD",
      "Retuned touch targets",
      "Multiplayer across platforms",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/baldurs-gate-enhanced-edition/id1491725178",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.beamdog.baldursgateee",
    thumbnail: "/images/games/baldurs-gate-enhanced.jpg",
    releaseYear: 2014,
  },
  {
    slug: "mini-metro",
    title: "Mini Metro",
    developer: "Dinosaur Polo Club",
    category: "puzzle",
    platforms: "both",
    tabletScore: 92,
    priceUsd: 4.99,
    shortDescription:
      "Transit puzzler with a minimal UI designed around two-thumb tablet play.",
    tabletFeatures: [
      "Multi-touch line drawing",
      "Perfect at any resolution",
      "Widescreen layout",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/mini-metro/id837860959",
    playStoreUrl: "https://play.google.com/store/apps/details?id=nz.co.codepoint.minimetro",
    thumbnail: "/images/games/mini-metro.jpg",
    releaseYear: 2015,
  },
  {
    slug: "kingdom-rush",
    title: "Kingdom Rush Vengeance",
    developer: "Ironhide Game Studio",
    category: "strategy",
    platforms: "both",
    tabletScore: 89,
    priceUsd: 1.99,
    shortDescription:
      "Tower defense where a tablet's size makes fast tower swaps and hero placement actually readable.",
    tabletFeatures: [
      "Wide HUD for tablets",
      "No ads on paid version",
      "Precision touch targets",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/kingdom-rush-vengeance-td/id1435745380",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.ironhidegames.android.kingdomrushvengeance",
    thumbnail: "/images/games/kingdom-rush.jpg",
    releaseYear: 2018,
  },
  {
    slug: "the-room-4",
    title: "The Room: Old Sins",
    developer: "Fireproof Games",
    category: "puzzle",
    platforms: "both",
    tabletScore: 94,
    priceUsd: 4.99,
    shortDescription:
      "Puzzle box series whose tactile pinch/rotate gestures genuinely need a tablet to breathe.",
    tabletFeatures: [
      "Tactile multi-touch puzzles",
      "High-fidelity 3D on iPad",
      "No IAP",
    ],
    appStoreUrl: "https://apps.apple.com/us/app/the-room-old-sins/id1394049550",
    playStoreUrl: "https://play.google.com/store/apps/details?id=com.FireproofStudios.TheRoom4",
    thumbnail: "/images/games/the-room-4.jpg",
    releaseYear: 2018,
  },
  {
    slug: "divinity-original-sin-2",
    title: "Divinity: Original Sin 2",
    developer: "Larian Studios",
    category: "rpg",
    platforms: "ios",
    tabletScore: 94,
    priceUsd: 24.99,
    shortDescription:
      "Larian's masterpiece CRPG rebuilt from the ground up for iPad with a native touch UI and full 4-player co-op.",
    tabletFeatures: [
      "Three control schemes: touch, controller, or keyboard/mouse",
      "Touch UI designed specifically for iPad (not ported phone UI)",
      "Local split-screen co-op for 2 players on a single tablet",
      "1440p visuals on iPad Pro matching PC resolution",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/divinity-original-sin-2.jpg",
    releaseYear: 2021,
  },
  {
    slug: "balatro",
    title: "Balatro",
    developer: "LocalThunk / Playstack",
    category: "strategy",
    platforms: "both",
    tabletScore: 93,
    priceUsd: 9.99,
    shortDescription:
      "The poker roguelike phenomenon that reviewers say feels better on iPad than on PC thanks to tactile card handling.",
    tabletFeatures: [
      "Mobile interface designed to outclass PC/console versions",
      "120fps support on ProMotion iPads",
      "Included free with Apple Arcade subscription",
      "Haptics and optional controller support",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/balatro.jpg",
    releaseYear: 2024,
  },
  {
    slug: "hades",
    title: "Hades",
    developer: "Supergiant Games",
    category: "action",
    platforms: "ios",
    tabletScore: 91,
    priceUsd: null,
    shortDescription:
      "Supergiant's roguelike action masterpiece plays flawlessly at 60fps on iPad via Netflix Games with full controller support.",
    tabletFeatures: [
      "60fps performance on iPad, redesigned touch UI",
      "Full controller support (Xbox, 8BitDo, etc.)",
      "Cloud saves sync between iPad and iPhone",
      "Offline play, no ads or IAP",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/hades.jpg",
    releaseYear: 2024,
  },
  {
    slug: "into-the-breach",
    title: "Into the Breach",
    developer: "Subset Games",
    category: "strategy",
    platforms: "both",
    tabletScore: 92,
    priceUsd: null,
    shortDescription:
      "Puzzle-perfect turn-based mech tactics from the FTL team with a touch UI rebuilt for tablet grid warfare.",
    tabletFeatures: [
      "Touch UI redesigned specifically for tablet play",
      "Full controller and Bluetooth mouse support on iPad",
      "Free with Netflix subscription, no ads",
      "Advanced Edition content included",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/into-the-breach.jpg",
    releaseYear: 2022,
  },
  {
    slug: "mini-motorways",
    title: "Mini Motorways",
    developer: "Dinosaur Polo Club",
    category: "simulation",
    platforms: "ios",
    tabletScore: 90,
    priceUsd: null,
    shortDescription:
      "Minimalist road-drawing city sim from the Mini Metro team, designed day-one for touch and best on a larger canvas.",
    tabletFeatures: [
      "iPad screen is the ideal canvas for drawing road networks",
      "Apple Arcade title with no ads or IAP",
      "Touch-first design, no controller cruft",
      "Pencil support for precise road placement",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/mini-motorways.jpg",
    releaseYear: 2019,
  },
  {
    slug: "terraforming-mars",
    title: "Terraforming Mars",
    developer: "Asmodee Digital / FryxGames",
    category: "board",
    platforms: "both",
    tabletScore: 88,
    priceUsd: 8.99,
    shortDescription:
      "The award-winning engine-building board game adapted with a UI that's explicitly best on tablet screens.",
    tabletFeatures: [
      "UI specifically designed for tablet touch (official word from Asmodee)",
      "Up to 5-player pass-and-play on a single iPad",
      "Cross-platform multiplayer with Steam/Android",
      "Full Colonies and Prelude DLC available",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/terraforming-mars.jpg",
    releaseYear: 2019,
  },
  {
    slug: "root-board-game",
    title: "Root",
    developer: "Dire Wolf Digital",
    category: "board",
    platforms: "both",
    tabletScore: 89,
    priceUsd: 9.99,
    shortDescription:
      "The asymmetric woodland war board game adapted with beautiful animations that bring the iPad board to life.",
    tabletFeatures: [
      "Pass-and-play local multiplayer on single iPad",
      "Online matchmaking via Dire Wolf servers",
      "Animated Kyle Ferrin artwork in near-3D",
      "35 scenario challenges + full tutorial",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/root-board-game.jpg",
    releaseYear: 2020,
  },
  {
    slug: "gloomhaven",
    title: "Gloomhaven",
    developer: "Flaming Fowl Studios / Asmodee Digital",
    category: "rpg",
    platforms: "ios",
    tabletScore: 87,
    priceUsd: 9.99,
    shortDescription:
      "The colossal tactical-RPG board game with 17 classes and 95+ scenarios, cleanly adapted for iPad's larger screen.",
    tabletFeatures: [
      "4.9/5 App Store rating, Editor's Choice award",
      "All 17 mercenary classes, 1,000+ abilities",
      "95-scenario branching campaign included",
      "Larger board and card text needs tablet real estate",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/gloomhaven.jpg",
    releaseYear: 2023,
  },
  {
    slug: "galaxy-trucker",
    title: "Galaxy Trucker",
    developer: "Czech Games Edition",
    category: "board",
    platforms: "both",
    tabletScore: 88,
    priceUsd: 4.99,
    shortDescription:
      "Vlaada Chvatil's frenetic ship-building board game with a turn-based digital mode designed around tablet pass-and-play.",
    tabletFeatures: [
      "Pass-and-play turn-based building mode for tablets",
      "Up to 4 players on a single iPad",
      "Async online multiplayer",
      "Bright large ship-building grid needs tablet space",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/galaxy-trucker.jpg",
    releaseYear: 2014,
  },
  {
    slug: "through-the-ages",
    title: "Through the Ages",
    developer: "Czech Games Edition",
    category: "board",
    platforms: "both",
    tabletScore: 87,
    priceUsd: 8.99,
    shortDescription:
      "Vlaada Chvatil's card-driven civ-lite board game widely regarded as one of the best digital board game adaptations.",
    tabletFeatures: [
      "30+ challenges with varying win conditions",
      "Async online multiplayer with cross-platform play",
      "Dense card UI that wants tablet screen space",
      "Robust AI with multiple difficulty tiers",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/through-the-ages.jpg",
    releaseYear: 2015,
  },
  {
    slug: "dune-imperium",
    title: "Dune: Imperium",
    developer: "Dire Wolf Digital",
    category: "board",
    platforms: "both",
    tabletScore: 87,
    priceUsd: 9.99,
    shortDescription:
      "The acclaimed deckbuilder/worker-placement hybrid with Dire Wolf's signature polish and a spacious tablet-ready board.",
    tabletFeatures: [
      "Board laid out to use full iPad canvas",
      "Solo, local AI, and online multiplayer modes",
      "House Hagal automated opponent for solo play",
      "Pass-and-play on single iPad",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/dune-imperium.jpg",
    releaseYear: 2023,
  },
  {
    slug: "wildfrost",
    title: "Wildfrost",
    developer: "Deadpan Games / Chucklefish",
    category: "strategy",
    platforms: "both",
    tabletScore: 88,
    priceUsd: 4.99,
    shortDescription:
      "A tactical deckbuilding roguelike whose iOS port is praised as superb and responsive, with 120fps on iPad Pro.",
    tabletFeatures: [
      "Full 120fps support on ProMotion iPads",
      "Native touch controls plus full controller support",
      "Free demo to beat first boss, then single IAP",
      "Card+board UI optimized for tablet tapping",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/wildfrost.jpg",
    releaseYear: 2024,
  },
  {
    slug: "fantasian-neo-dimension",
    title: "Fantasian Neo Dimension",
    developer: "Mistwalker",
    category: "rpg",
    platforms: "ios",
    tabletScore: 89,
    priceUsd: null,
    shortDescription:
      "Sakaguchi's JRPG built from hand-crafted physical dioramas, originally Apple Arcade-exclusive and designed around iPad's display.",
    tabletFeatures: [
      "Hand-crafted dioramas photographed for each area",
      "Originally designed for Apple Arcade/iPad first",
      "Music by Nobuo Uematsu, voice acting in EN/JP",
      "Rebalanced 'Normal' mode tuned for touchscreen pacing",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/fantasian-neo-dimension.jpg",
    releaseYear: 2021,
  },
  {
    slug: "oceanhorn-2",
    title: "Oceanhorn 2: Knights of the Lost Realm",
    developer: "Cornfox & Bros.",
    category: "action",
    platforms: "ios",
    tabletScore: 87,
    priceUsd: null,
    shortDescription:
      "Zelda-inspired action-RPG built as an Apple Arcade flagship, engineered to feel like a console title on iPad.",
    tabletFeatures: [
      "Custom touch control scheme designed for tablets",
      "Full MFi/Xbox/PS controller support",
      "Apple Arcade exclusive, no IAP",
      "Console-quality graphics scaled for iPad Pro",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/oceanhorn-2.jpg",
    releaseYear: 2019,
  },
  {
    slug: "vampire-survivors",
    title: "Vampire Survivors",
    developer: "Poncle",
    category: "action",
    platforms: "both",
    tabletScore: 85,
    priceUsd: null,
    shortDescription:
      "The bullet-hell roguelike phenomenon that runs silky on iPad Pro and supports full 4-player couch co-op on one tablet.",
    tabletFeatures: [
      "1-4 player couch co-op on a single iPad",
      "Portrait or landscape modes for tablets",
      "Stable high framerate on iPad Pro",
      "Free to play with paid DLC packs",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/vampire-survivors.jpg",
    releaseYear: 2022,
  },
  {
    slug: "unpacking",
    title: "Unpacking",
    developer: "Witch Beam / Humble Games",
    category: "puzzle",
    platforms: "both",
    tabletScore: 87,
    priceUsd: 9.99,
    shortDescription:
      "The cozy Zen-puzzle game about unpacking a life across eight moves, with TouchArcade declaring it best on iPad.",
    tabletFeatures: [
      "Pixel-art detail only legible at tablet scale",
      "Smooth drag-and-drop designed for touch",
      "Full controller support optional",
      "Cheaper on mobile than PC/console",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/unpacking.jpg",
    releaseYear: 2023,
  },
  {
    slug: "chants-of-sennaar",
    title: "Chants of Sennaar",
    developer: "Rundisc / Playdigious",
    category: "puzzle",
    platforms: "both",
    tabletScore: 88,
    priceUsd: 9.99,
    shortDescription:
      "A language-deciphering puzzle adventure whose glyph-notebook mechanic feels made for tapping on an iPad screen.",
    tabletFeatures: [
      "Language-notebook mechanic perfect for touch annotations",
      "Great touchscreen support on iPad Pro",
      "Optional controller support",
      "Free-to-try with single full-unlock IAP",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/chants-of-sennaar.jpg",
    releaseYear: 2024,
  },
  {
    slug: "townscaper",
    title: "Townscaper",
    developer: "Oskar Stalberg / Raw Fury",
    category: "simulation",
    platforms: "both",
    tabletScore: 89,
    priceUsd: 4.99,
    shortDescription:
      "A meditative procedural town-building toy whose wide canvas and tap-to-place design feel purpose-built for iPad.",
    tabletFeatures: [
      "Wide canvas needs tablet screen real estate",
      "Pencil support for precise block placement",
      "No goals, no menus - pure creative play",
      "Runs flawlessly on older iPads",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/townscaper.jpg",
    releaseYear: 2021,
  },
  {
    slug: "crashlands-2",
    title: "Crashlands 2",
    developer: "Butterscotch Shenanigans",
    category: "rpg",
    platforms: "both",
    tabletScore: 88,
    priceUsd: 9.99,
    shortDescription:
      "A sprawling open-world crafting ARPG with 35+ hours of content, saves syncing cleanly between iPad, iPhone and Steam Deck.",
    tabletFeatures: [
      "Cross-progression between iPad, iPhone and Steam Deck",
      "Touch-first UI, no controller required",
      "No ads, no IAP, one-time purchase",
      "Expansive inventory UI benefits from tablet space",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/crashlands-2.jpg",
    releaseYear: 2025,
  },
  {
    slug: "dead-cells",
    title: "Dead Cells",
    developer: "Motion Twin / Playdigious",
    category: "action",
    platforms: "both",
    tabletScore: 86,
    priceUsd: 4.99,
    shortDescription:
      "The benchmark mobile roguelike Metroidvania with a tight touch control scheme redesigned specifically for tablets.",
    tabletFeatures: [
      "Touch controls redesigned ground-up for mobile",
      "Full MFi controller support",
      "Cross-save support on Apple Arcade version",
      "All console DLC available",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/dead-cells.jpg",
    releaseYear: 2019,
  },
  {
    slug: "sayonara-wild-hearts",
    title: "Sayonara Wild Hearts",
    developer: "Simogo / Annapurna Interactive",
    category: "action",
    platforms: "ios",
    tabletScore: 88,
    priceUsd: null,
    shortDescription:
      "Apple Arcade's 2019 Game of the Year - a pop-album rhythm ride that looks gorgeous on iPad and controls perfectly via touch.",
    tabletFeatures: [
      "Swipe/tap controls authored for touch, not ported",
      "Apple Arcade flagship, no IAP",
      "ProMotion 120Hz on iPad Pro",
      "Runs on older iPads down to iPad Air 2",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/sayonara-wild-hearts.jpg",
    releaseYear: 2019,
  },
  {
    slug: "alba-wildlife-adventure",
    title: "Alba: A Wildlife Adventure",
    developer: "ustwo games",
    category: "simulation",
    platforms: "ios",
    tabletScore: 85,
    priceUsd: null,
    shortDescription:
      "From the Monument Valley team, a cozy exploration game about protecting a Mediterranean island - iPad Pro's photography UI shines here.",
    tabletFeatures: [
      "In-game photo app benefits from tablet screen",
      "Apple Arcade exclusive, family-friendly",
      "iPad Pro + DualShock 4 described as seamless",
      "Short 4-6 hour meaningful experience",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/alba-wildlife-adventure.jpg",
    releaseYear: 2020,
  },
  {
    slug: "assemble-with-care",
    title: "Assemble with Care",
    developer: "ustwo games",
    category: "puzzle",
    platforms: "ios",
    tabletScore: 86,
    priceUsd: 2.99,
    shortDescription:
      "ustwo's tactile narrative-puzzler about repairing objects - disassembly gestures feel native to iPad multi-touch.",
    tabletFeatures: [
      "Pinch/rotate gestures designed for tablet multi-touch",
      "4-5 hour complete narrative, no IAP after unlock",
      "Object detail rewards larger screens",
      "From the Monument Valley studio",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/assemble-with-care.jpg",
    releaseYear: 2019,
  },
  {
    slug: "florence",
    title: "Florence",
    developer: "Mountains / Annapurna Interactive",
    category: "puzzle",
    platforms: "both",
    tabletScore: 87,
    priceUsd: 2.99,
    shortDescription:
      "A short interactive storybook about first love from Monument Valley's lead designer, built entirely around touch vignettes.",
    tabletFeatures: [
      "Each chapter uses a different touch-only mini-game",
      "Storybook panel layout uses tablet aspect ratio beautifully",
      "One-time purchase, no ads or IAP",
      "45-min emotional complete experience",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/florence.jpg",
    releaseYear: 2018,
  },
  {
    slug: "machinarium",
    title: "Machinarium",
    developer: "Amanita Design",
    category: "puzzle",
    platforms: "both",
    tabletScore: 86,
    priceUsd: 4.99,
    shortDescription:
      "Amanita's hand-painted point-and-click classic whose every scene looks like a gallery piece on an iPad screen.",
    tabletFeatures: [
      "Hand-painted 2D art renders beautifully at tablet resolution",
      "Tap-and-drag interaction feels native",
      "Apple Pencil-friendly for sketched in-game hint notes",
      "Self-contained, no IAP",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/machinarium.jpg",
    releaseYear: 2011,
  },
  {
    slug: "kingdom-two-crowns",
    title: "Kingdom: Two Crowns",
    developer: "Noio / Raw Fury",
    category: "strategy",
    platforms: "both",
    tabletScore: 85,
    priceUsd: 9.99,
    shortDescription:
      "A minimalist side-scrolling strategy/base-builder whose 2D parallax landscape fills the iPad's widescreen beautifully.",
    tabletFeatures: [
      "Wide 2D landscape suits tablet landscape mode",
      "Local co-op: two monarchs on one iPad",
      "Pixel art scales sharply on Retina displays",
      "No IAP, no ads",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/kingdom-two-crowns.jpg",
    releaseYear: 2020,
  },
  {
    slug: "lost-in-play",
    title: "Lost in Play",
    developer: "Happy Juice Games / Snapbreak",
    category: "puzzle",
    platforms: "both",
    tabletScore: 86,
    priceUsd: 6.99,
    shortDescription:
      "A Saturday-morning-cartoon point-and-click about two siblings, with hand-drawn animation that pops at iPad resolution.",
    tabletFeatures: [
      "Hand-drawn animation scales cleanly on iPad",
      "Tap-only controls ideal for touch",
      "No ads, no IAP, all-ages friendly",
      "5-hour complete narrative",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/lost-in-play.jpg",
    releaseYear: 2022,
  },
  {
    slug: "pocket-city",
    title: "Pocket City",
    developer: "Codebrew Games",
    category: "simulation",
    platforms: "both",
    tabletScore: 84,
    priceUsd: 4.99,
    shortDescription:
      "A premium SimCity-like city builder with a clean touch UI that was built for mobile-first but really opens up on iPad.",
    tabletFeatures: [
      "Zoning menus need tablet screen space",
      "No ads, no IAP, one-time purchase",
      "Touch-first UI, not a phone-to-PC port",
      "Disaster simulations feel great on big screen",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/pocket-city.jpg",
    releaseYear: 2018,
  },
  {
    slug: "two-point-hospital",
    title: "Two Point Hospital",
    developer: "Two Point Studios / Sega",
    category: "simulation",
    platforms: "both",
    tabletScore: 84,
    priceUsd: null,
    shortDescription:
      "The spiritual successor to Theme Hospital, brought to iPad via Netflix with a UI reworked for touch-first management.",
    tabletFeatures: [
      "Netflix subscription = no IAP, no ads",
      "UI reworked for tablet-sized touch targets",
      "Full console content included",
      "Better cross-save than the Switch version per reviewers",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/two-point-hospital.jpg",
    releaseYear: 2023,
  },
  {
    slug: "inkulinati",
    title: "Inkulinati",
    developer: "Yaza Games / Daedalic",
    category: "strategy",
    platforms: "ios",
    tabletScore: 84,
    priceUsd: null,
    shortDescription:
      "A turn-based tactics game drawn in medieval manuscript style, served on Apple Arcade and beautifully legible on iPad.",
    tabletFeatures: [
      "Medieval-manuscript art renders sharply on iPad",
      "Apple Arcade exclusive, no ads or IAP",
      "Turn-based grid combat ideal for tapping",
      "Roguelite Journey Mode for quick sessions",
    ],
    appStoreUrl: null,
    playStoreUrl: null,
    thumbnail: "/images/games/inkulinati.jpg",
    releaseYear: 2024,
  },
];

async function main() {
  console.log(`Seeding ${SEED_GAMES.length} games…`);
  for (const g of SEED_GAMES) {
    await pool.query(
      `INSERT INTO games (
         slug, title, developer, category, platforms, tablet_score,
         price_usd, short_description, tablet_features,
         app_store_url, play_store_url, thumbnail, release_year
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
       ON CONFLICT (slug) DO UPDATE SET
         title = EXCLUDED.title,
         developer = EXCLUDED.developer,
         category = EXCLUDED.category,
         platforms = EXCLUDED.platforms,
         tablet_score = EXCLUDED.tablet_score,
         price_usd = EXCLUDED.price_usd,
         short_description = EXCLUDED.short_description,
         tablet_features = EXCLUDED.tablet_features,
         app_store_url = EXCLUDED.app_store_url,
         play_store_url = EXCLUDED.play_store_url,
         thumbnail = EXCLUDED.thumbnail,
         release_year = EXCLUDED.release_year,
         updated_at = NOW()`,
      [
        g.slug,
        g.title,
        g.developer,
        g.category,
        g.platforms,
        g.tabletScore,
        g.priceUsd,
        g.shortDescription,
        g.tabletFeatures,
        g.appStoreUrl,
        g.playStoreUrl,
        g.thumbnail,
        g.releaseYear,
      ],
    );
    console.log(`  ✓ ${g.title}`);
  }
  console.log("Done.");
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
